<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $company->name }} - Profile</title>
    <style>
        body { font-family: sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { max-width: 150px; max-height: 100px; }
        h1 { margin: 10px 0 5px 0; color: #111827; }
        .business-type { color: #6b7280; font-size: 14px; margin-bottom: 10px; }
        .section-title { background-color: #f3f4f6; padding: 10px; margin-top: 30px; margin-bottom: 15px; font-weight: bold; border-left: 4px solid #10b981; }
        .grid { width: 100%; display: table; }
        .col { display: table-cell; width: 50%; padding-right: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border-bottom: 1px solid #e5e7eb; padding: 8px 4px; text-align: left; }
        th { width: 40%; color: #6b7280; font-weight: normal; font-size: 12px; }
        td { font-weight: bold; font-size: 14px; }
        .branches { margin-top: 20px; }
        .branch-item { border: 1px solid #e5e7eb; padding: 15px; margin-bottom: 10px; border-radius: 5px; }
        .branch-name { font-weight: bold; margin-bottom: 5px; }
        .branch-address { font-size: 12px; color: #6b7280; }
        .about-text { white-space: pre-wrap; font-size: 14px; color: #4b5563; }
        .footer { position: fixed; bottom: -30px; left: 0; right: 0; height: 30px; text-align: center; color: #9ca3af; font-size: 10px; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        @if($company->logo)
            <img src="{{ public_path('storage/' . $company->logo) }}" class="logo" alt="{{ $company->name }}">
        @endif
        <h1>{{ $company->name }}</h1>
        @if($company->business_type)
            <div class="business-type">{{ $company->business_type }}</div>
        @endif
        <div style="font-size: 12px;">
            @if($company->email) {{ $company->email }} @endif
            @if($company->phone) | {{ $company->phone }} @endif
            @if($company->website) | {{ $company->website }} @endif
        </div>
    </div>

    <div class="section-title">Business Information</div>
    <div class="grid">
        <div class="col">
            <table>
                <tr><th>Established</th><td>{{ $company->year_established ?? 'N/A' }}</td></tr>
                <tr><th>Registration No.</th><td>{{ $company->registration_number ?? 'N/A' }}</td></tr>
                <tr><th>Tax ID</th><td>{{ $company->tax_id ?? 'N/A' }}</td></tr>
            </table>
        </div>
        <div class="col">
            <table>
                <tr><th>Trade License</th><td>{{ $company->trade_license_number ?? 'N/A' }}</td></tr>
                <tr><th>VAT Number</th><td>{{ $company->vat_registration_number ?? 'N/A' }}</td></tr>
                <tr><th>Alternative Phone</th><td>{{ $company->alternative_phone ?? 'N/A' }}</td></tr>
            </table>
        </div>
    </div>

    @if($company->about_company)
    <div class="section-title">About Us</div>
    <div class="about-text">{{ $company->about_company }}</div>
    @endif

    <div class="section-title">Our Branches</div>
    @if($company->branches->count() > 0)
        <div class="branches">
            @foreach($company->branches as $branch)
                <div class="branch-item">
                    <div class="branch-name">{{ $branch->name }}</div>
                    <div class="branch-address">{{ $branch->address }}</div>
                    @if($branch->phone)
                        <div class="branch-address" style="margin-top: 5px;">📞 {{ $branch->phone }}</div>
                    @endif
                </div>
            @endforeach
        </div>
    @else
        <p style="font-size: 14px; color: #6b7280; font-style: italic;">No branches available for display.</p>
    @endif

    <div class="footer">
        Generated by Pharma Point Management System on {{ now()->format('d M Y, h:i A') }}
    </div>
</body>
</html>
